In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures

# READ THE BANGALORE HOUSE PRICE DATASET
house_data = pd.read_csv('C:/Users/Admin/Documents/arc_model_core/ml_docs/Datasets/banglore_house_price.csv')

print(f":> SHAPE OF DATASET: {house_data.shape}")
house_data.head(10)

:> SHAPE OF DATASET: (499, 9)

,Area_type,Availability,Location,Size,Society,Total_sqft,Bath,Balcony,Price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00

In [2]:
# DEFINE COLUMNS FOR CATEGORICAL VALUE COUNT ANALYSIS
categorical_columns = [
    "Area_type",
    "Availability",
    "Balcony",
    "Bath",
    "Location",
    "Price",
    "Size",
    "Society",
    "Total_sqft",
]

# DISPLAY VALUE COUNTS FOR EACH CATEGORICAL COLUMN
for col in categorical_columns:
    print(f"\n\n<<========== {col.upper()} VALUE COUNTs ==========>>")
    display(house_data[col].value_counts())

<<========== AREA_TYPE VALUE COUNTs ==========>>

Area_type
Super built-up  Area    332
Built-up  Area           90
Plot  Area               74
Carpet  Area              3
Name: count, dtype: int64

<<========== AVAILABILITY VALUE COUNTs ==========>>

Availability
Ready To Move    398
18-May            11
18-Apr            10
18-Dec             8
19-Dec             7
18-Aug             6
21-Dec             4
18-Mar             4
19-Mar             4
18-Jun             4
20-Dec             3
18-Oct             3
19-Jan             3
18-Jul             3
21-Jun             3
19-Apr             2
17-Jul             2
18-Sep             2
18-Feb             1
18-Nov             1
17-Oct             1
19-Sep             1
20-Sep             1
20-Feb             1
20-Aug             1
17-Sep             1
17-Aug             1
22-Dec             1
22-Jan             1
20-May             1
19-Aug             1
17-May             1
17-Jun             1
21-May             1
18-Jan             1
20-Mar             1
17-Dec             1
16-Mar             1
19-Jun             1
22-Jun             1
Name: count, dtype: int64

<<========== BALCONY VALUE COUNTs ==========>>

Balcony
2.0    201
1.0    174
3.0     62
0.0     40
Name: count, dtype: int64

<<========== BATH VALUE COUNTs ==========>>

Bath
2.0    258
3.0    130
4.0     42
1.0     28
5.0     15
6.0      9
7.0      7
8.0      4
9.0      2
Name: count, dtype: int64

<<========== LOCATION VALUE COUNTs ==========>>

Location
Electronic City       21
Whitefield            17
Kanakpura Road        12
Sarjapur  Road        11
7th Phase JP Nagar    10
                      ..
Bank Avenue            1
Surabhi Layout         1
Banjara Layout         1
Omkar Nagar            1
Kereguddadahalli       1
Name: count, Length: 261, dtype: int64

<<========== PRICE VALUE COUNTs ==========>>

Price
55.00     13
65.00     13
60.00     10
75.00     10
120.00     9
          ..
50.17      1
49.00      1
337.00     1
94.42      1
52.50      1
Name: count, Length: 243, dtype: int64

<<========== SIZE VALUE COUNTs ==========>>

Size
2 BHK        207
3 BHK        159
4 Bedroom     30
3 Bedroom     21
4 BHK         19
1 BHK         15
2 Bedroom     14
6 Bedroom     10
8 Bedroom      6
5 Bedroom      6
1 Bedroom      2
7 Bedroom      2
5 BHK          2
7 BHK          2
6 BHK          2
1 RK           1
11 BHK         1
Name: count, dtype: int64

<<========== SOCIETY VALUE COUNTs ==========>>

Society
GMown E    6
GrrvaGr    5
Prarkun    5
SunceEs    4
Prityel    3
          ..
Brica E    1
GoAirej    1
Prenty     1
Shinei     1
Apows M    1
Name: count, Length: 270, dtype: int64

<<========== TOTAL_SQFT VALUE COUNTs ==========>>

Total_sqft
1200    36
1000    10
1500     9
1100     8
1800     7
        ..
4800     1
929      1
1753     1
4500     1
1196     1
Name: count, Length: 298, dtype: int64

In [3]:
# DROP IRRELEVANT FEATURES FROM THE DATASET
data_after_drop = house_data.drop(['Area_type', 'Availability', 'Balcony', 'Society'], axis=1)
display(data_after_drop.head(10))

                   Location       Size Total_sqft  Bath   Price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00
5                Whitefield      2 BHK       1170   2.0   38.00
6          Old Airport Road      4 BHK       2732   4.0  204.00
7              Rajaji Nagar      4 BHK       3300   4.0  600.00
8              Marathahalli      3 BHK       1310   3.0   63.25
9              Gandhi Bazar  6 Bedroom       1020   6.0  370.00

In [4]:
# REMOVE ROWS WITH MISSING VALUES
data_clean = data_after_drop.dropna()

# DISPLAY SHAPE AFTER DROPPING FEATURES AND NULL VALUES
print(f":> DATASET SHAPE AFTER DROPPING SELECTED FEATURES: {data_after_drop.shape}")
print(f":> DATASET SHAPE AFTER DROPPING NULL VALUES: {data_clean.shape}")


# DISPLAY MISSING VALUE COUNTS BEFORE AND AFTER CLEANING
print("\n=>> MISSING VALUE COUNT (BEFORE DROPPING NULLS) >>")
display(data_after_drop.isnull().sum())

print("\n=>> MISSING VALUE COUNT (AFTER DROPPING NULLS) >>")
display(data_clean.isnull().sum())

:> DATASET SHAPE AFTER DROPPING SELECTED FEATURES: (499, 5)
:> DATASET SHAPE AFTER DROPPING NULL VALUES: (495, 5)

=>> MISSING VALUE COUNT (BEFORE DROPPING NULLS) >>

Location      0
Size          0
Total_sqft    0
Bath          4
Price         0
dtype: int64

=>> MISSING VALUE COUNT (AFTER DROPPING NULLS) >>

Location      0
Size          0
Total_sqft    0
Bath          0
Price         0
dtype: int64

In [5]:
# CHECK DATA TYPES OF THE CLEANED DATASET
data_clean.dtypes

Location          str
Size              str
Total_sqft        str
Bath          float64
Price         float64
dtype: object

In [6]:
# CLEAN 'SIZE' COLUMN: EXTRACT NUMERIC PART (e.g., "2 BHK" -> 2)
data_clean['BHK'] = data_clean['Size'].apply(lambda x: int(x.split(" ")[0]))

# DROP THE ORIGINAL 'SIZE' COLUMN AFTER EXTRACTION
data_without_size = data_clean.drop('Size', axis=1)

In [7]:
# FUNCTION TO CONVERT 'Total_sqft' TO NUMERIC VALUES
def CONVERT_SQFT_TO_FLOAT(x):
    """
    Convert square feet values to float.
    Handles ranges like '1200-1500' by taking the average.
    """
    try:
        if '_' in str(x):
            nums = x.split('_')
            return (float(nums[0]) + float(nums[1])) / 2
        return float(x)
    except:
        return np.nan

# APPLY THE CONVERSION FUNCTION TO 'Total_sqft' COLUMN
data_without_size['Total_sqft'] = data_without_size['Total_sqft'].apply(CONVERT_SQFT_TO_FLOAT)

# REMOVE ANY ROWS WITH NULL VALUES AFTER CONVERSION
final_clean_data = data_without_size.dropna()

# APPLY ONE-HOT ENCODING TO THE 'Location' COLUMN
encoded_data = pd.get_dummies(final_clean_data, columns=['Location'], drop_first=True)

In [8]:
# SEPARATE FEATURES (X) AND TARGET VARIABLE (y)
X = encoded_data.drop('Price', axis=1)
y = encoded_data['Price']

# SPLIT THE DATA INTO TRAINING AND TESTING SETS (80% TRAIN, 20% TEST)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# DISPLAY THE SHAPES OF ALL DATASETS
print(f":> FEATURES SHAPE (X): {X.shape}")
print(f":> TARGET SHAPE (y): {y.shape}")

print(f"\n:> TRAINING FEATURES SHAPE (X_train): {X_train.shape}")
print(f":> TESTING FEATURES SHAPE (X_test): {X_test.shape}")
print(f":> TRAINING TARGET SHAPE (y_train): {y_train.shape}")
print(f":> TESTING TARGET SHAPE (y_test): {y_test.shape}")

:> FEATURES SHAPE (X): (489, 263)
:> TARGET SHAPE (y): (489,)

:> TRAINING FEATURES SHAPE (X_train): (391, 263)
:> TESTING FEATURES SHAPE (X_test): (98, 263)
:> TRAINING TARGET SHAPE (y_train): (391,)
:> TESTING TARGET SHAPE (y_test): (98,)

In [9]:
scaler = StandardScaler()                           # INITIALIZE STANDARD SCALER FOR FEATURE NORMALIZATION
linear = LinearRegression()                         # INITIALIZE LINEAR REGRESSION
polynomial = PolynomialFeatures(degree=2)           # INITIALIZE POLYNOMIAL FEATURES (DEGREE 2)

# APPLY STANDARD SCALING TO TRAINING AND TEST DATA
X_train = scaler.fit_transform(X_train)             # FIT AND TRANSFORM ON TRAINING DATA
X_test = scaler.transform(X_test)                   # ONLY TRANSFORM ON TESTING DATA


# GENERATE POLYNOMIAL FEATURES FROM SCALED DATA
X_train_Pol = polynomial.fit_transform(X_train)
X_test_Pol = polynomial.transform(X_test)

# DISPLAY THE SHAPE OF POLYNOMIAL FEATURES
print(f":> POLYNOMIAL FEATURES SHAPE (TRAIN): {X_train_Pol.shape}")
print(f":> POLYNOMIAL FEATURES SHAPE (TEST): {X_test_Pol.shape}")


# TRAIN LINEAR REGRESSION MODEL ON POLYNOMIAL FEATURES
linear.fit(X_train_Pol, y_train)


# CALCULATE AND DISPLAY MODEL ACCURACY (R² SCORE)
model_score = linear.score(X_test_Pol, y_test)
print(f"\n:> MODEL R² SCORE ON TEST DATA: {model_score:.4f}")


# MAKE PREDICTION FOR THE FIRST TEST SAMPLE
single_prediction = linear.predict([X_test_Pol[0, :]])
print(f"\n:> PREDICTED PRICE FOR FIRST TEST SAMPLE: {single_prediction[0]:,.2f}")

# MAKE PREDICTIONS ON THE ENTIRE TEST SET
y_pred = linear.predict(X_test_Pol)

:> POLYNOMIAL FEATURES SHAPE (TRAIN): (391, 34980)
:> POLYNOMIAL FEATURES SHAPE (TEST): (98, 34980)

:> MODEL R² SCORE ON TEST DATA: -3.8755

:> PREDICTED PRICE FOR FIRST TEST SAMPLE: -20.92

In [10]:
# DISPLAY ACTUAL VS PREDICTED VALUES
print("\n:> PREDICTED PRICES (First 10):")
display(y_pred[:10])

print("\n:> ACTUAL PRICES (First 10):")
display(y_test[:10].values)

:> PREDICTED PRICES (First 10):

array([-20.91897321,  26.49350866,  83.80499049,  74.87679037,
       -34.54612528, 156.80427508,  41.        , 226.8550844 ,
        79.37603428,  33.94286108])

:> ACTUAL PRICES (First 10):

array([ 35.23,  37.  , 100.  ,  65.  ,  40.  ,  83.09,  35.  , 119.  ,
        94.42,  60.  ])

In [12]:
# CALCULATE EVALUATION METRICS
MSE = mean_squared_error(y_test, y_pred)            # MEAN SQUARED ERROR
RMSE = np.sqrt(MSE)                                 # ROOT MEAN SQUARED ERROR

# DISPLAY THE EVALUATION METRICS
print("=" * 50)
print(f"=>> MODEL EVALUATION METRICS >>")
print("=" * 50)
print(f":> MEAN SQUARED ERROR (MSE): {MSE:.2f}")
print(f":> ROOT MEAN SQUARED ERROR (RMSE): {RMSE:.2f}")
print("=" * 50)

==================================================
=>> MODEL EVALUATION METRICS >>
==================================================
:> MEAN SQUARED ERROR (MSE): 76710.86
:> ROOT MEAN SQUARED ERROR (RMSE): 276.97
==================================================