In [61]:
# IMPORT THE REQUIRED LIBRARIES FOR DATA
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# READ THE TRAINING AND TEST DATASETS FROM CSV FILES
train_DF = pd.read_csv("trained_dataset.csv")
test_DF = pd.read_csv("test_dataset.csv")

# DISPLAY ALL ROWS AND COLUMNS WITHOUT TRUNCATION FOR FULL INSPECTION
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# DISPLAY THE DIMENSIONS OF BOTH DATASETS
print(f":> TRAINING DATASET SHAPE: {train_DF.shape}")
print(f":> TEST DATASET SHAPE: {test_DF.shape}")

:> TRAINING DATASET SHAPE: (1460, 81)
:> TEST DATASET SHAPE: (1459, 80)

In [62]:
# SEPARATE FEATURES AND TARGET VARIABLE FROM TRAINING DATA
X_train = train_DF.drop(columns='SalePrice')
y_train = train_DF['SalePrice']

# CREATE A COPY OF TEST DATASET FOR FEATURES
X_test = test_DF.copy()

# CALCULATE MISSING VALUES COUNT FOR EACH COLUMN
Null_Val = X_train.isnull().sum()

# IDENTIFY NUMERICAL AND CATEGORICAL COLUMNS
Numric_Cols = X_train.select_dtypes(include=['int64', 'float64']).columns
Cate_Cols = X_train.select_dtypes(include=['object']).columns

# FILTER ONLY THOSE COLUMNS THAT HAVE MISSING VALUES
Drp_Numric_Cols = [i for i in Numric_Cols if Null_Val[i] > 0]
Drp_Cate_Cols = [i for i in Cate_Cols if Null_Val[i] > 0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_15988\1890847959.py:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Cate_Cols = X_train.select_dtypes(include=['object']).columns

In [63]:
# DISPLAY COLUMNS WITH MISSING VALUES BY DATA TYPE
print(f":> NUMERICAL COLUMNS CONTAINING MISSING VALUES: {Drp_Numric_Cols}")
print(f":> CATEGORICAL COLUMNS CONTAINING MISSING VALUES: {Drp_Cate_Cols}")

display(train_DF[Drp_Numric_Cols].isnull().sum())       # DISPLAY MISSING VALUE COUNTS FOR NUMERICAL COLUMNS
display(train_DF[Drp_Cate_Cols].isnull().sum())         # DISPLAY MISSING VALUE COUNTS FOR CATEGORICAL COLUMNS

:> NUMERICAL COLUMNS CONTAINING MISSING VALUES: ['LotFrontage', 'MasVnrArea', 'GarageYrBlt']
:> CATEGORICAL COLUMNS CONTAINING MISSING VALUES: ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature']

LotFrontage    259
MasVnrArea       8
GarageYrBlt     81
dtype: int64

Alley           1369
MasVnrType       872
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [ ]:
# For_Mean_Cols = [col for col in Drp_Numric_Cols if X_train[col].nunique() > 20]                 # USE MEAN FOR CONTINUOUS NUMERICAL FEATURES
# For_Median_Cols = [col for col in Drp_Numric_Cols if X_train[col].nunique() <= 20]              # USE MEDIAN FOR SKEWED / SMALL NUMERICAL FEATURES
# For_Mode_Cols = [col for col in Drp_Cate_Cols if X_train[col].isnull().mean() < 0.5]            # USE MODE FOR NORMAL CATEGORICAL FEATURES
# For_Missing_Cols = [col for col in Drp_Cate_Cols if X_train[col].isnull().mean() >= 0.5]        # USE "missing" IF TOO MANY NULL VALUES

# # DISPLAY RESULTS
# print(f":> MEAN COLS: {For_Mean_Cols}")
# print(f":> MEDIAN COLS: {For_Median_Cols}")
# print(f":> MODE COLS: {For_Mode_Cols}")
# print(f":> MISSING COLS: {For_Missing_Cols}")

# # NOTE: IT'S ADVANCED METHODS TO CALCULATE DIFFERENT CSV FILE VALUEs (AUTOMATIC SELECTION)

:> MEAN COLS: ['LotFrontage', 'MasVnrArea', 'GarageYrBlt']
:> MEDIAN COLS: []
:> MODE COLS: ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']
:> MISSING COLS: ['Alley', 'MasVnrType', 'PoolQC', 'Fence', 'MiscFeature']

In [ ]:
# DEFINE COLUMNS TO BE IMPUTED WITH MEAN STRATEGY
For_Mean_Cols = ["LotFrontage"]

# DEFINE COLUMNS TO BE IMPUTED WITH MEDIAN STRATEGY
For_Median_Cols = ["MasVnrArea", "GarageYrBlt"]

# DEFINE COLUMNS TO BE IMPUTED WITH MODE (MOST FREQUENT) STRATEGY
For_Mode_Cols = [
    "Alley",
    "MasVnrType",
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "Electrical",
    "FireplaceQu",
]

# DEFINE COLUMNS TO BE IMPUTED WITH CONSTANT VALUE "missing"
For_Missing_Cols = [
    "GarageType",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "PoolQC",
    "Fence",
    "MiscFeature",
]


# CREATE PIPELINES FOR DIFFERENT IMPUTATION STRATEGIES
Mean_Impute = Pipeline(steps=[("imputer", SimpleImputer(strategy="mean"))])
Median_Impute = Pipeline(steps=[("imputer", SimpleImputer(strategy="median"))])
Mode_Impute = Pipeline(steps=[("imputer", SimpleImputer(strategy="most_frequent"))])
Missing_Impute = Pipeline(steps=[("imputer", SimpleImputer(strategy="constant", fill_value="missing"))])

# CREATE COLUMN TRANSFORMER TO APPLY DIFFERENT STRATEGIES TO SPECIFIC COLUMNS
preprocessor = ColumnTransformer(transformers=[
    ('mean_imputer', Mean_Impute, For_Mean_Cols),
    ('median_imputer', Median_Impute, For_Median_Cols),
    ('mode_imputer', Mode_Impute, For_Mode_Cols),
    ('missing_imputer', Missing_Impute, For_Missing_Cols),
])

In [66]:
# FIT THE PREPROCESSOR ON BOTH TRAINING AND TEST DATA
preprocessor.fit(X_train)
# preprocessor.fit(X_test)

# EXTRACT THE CALCULATED STATISTICS FROM EACH IMPUTER
Mean_Values = preprocessor.named_transformers_["mean_imputer"].named_steps["imputer"].statistics_
Median_Values = preprocessor.named_transformers_["median_imputer"].named_steps["imputer"].statistics_
Mode_Values = preprocessor.named_transformers_["mode_imputer"].named_steps["imputer"].statistics_

# TRANSFORM BOTH TRAINING AND TEST DATASETS
Clean_X_train = preprocessor.transform(X_train)
Clean_X_test = preprocessor.transform(X_test)

# DISPLAY THE TRANSFORMED TRAINING DATA
print(":> TRAINING DATA AFTER IMPUTATION (ALL STRATEGIES APPLIED) >>")
display(Clean_X_train)

# DISPLAY THE TRANSFORMED TEST DATA
print("\n:> TEST DATA AFTER IMPUTATION (ALL STRATEGIES APPLIED) >>")
display(Clean_X_test)

AttributeError: 'SimpleImputer' object has no attribute 'statistics_'

In [ ]:
# DISPLAY THE TRANSFORMERS CONFIGURATION FOR VERIFICATION
print(preprocessor.transformers_)

[('mean_imputer', Pipeline(steps=[('imputer', SimpleImputer())]), ['LotFrontage']), ('median_imputer', Pipeline(steps=[('imputer', SimpleImputer(strategy='median'))]), ['MasVnrArea', 'GarageYrBlt']), ('mode_imputer', Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent'))]), ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu']), ('missing_imputer', Pipeline(steps=[('imputer',
                 SimpleImputer(fill_value='missing', strategy='constant'))]), ['GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature']), ('remainder', 'drop', ['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageCars', 'GarageArea', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition'])]

In [ ]:
# CONVERT TRANSFORMED ARRAYS BACK TO DATAFRAMES FOR BETTER VISUALIZATION
Complete_X_train = pd.DataFrame(Clean_X_train, columns=For_Mean_Cols + For_Median_Cols + For_Mode_Cols + For_Missing_Cols)
Complete_X_test = pd.DataFrame(Clean_X_test, columns=For_Mean_Cols + For_Median_Cols + For_Mode_Cols + For_Missing_Cols)

In [ ]:
# DISPLAY THE COMPLETE CLEANED TRAINING DATAFRAME
display(Complete_X_train)

     LotFrontage MasVnrArea GarageYrBlt Alley MasVnrType BsmtQual BsmtCond  \
0           65.0      196.0      2003.0  Grvl    BrkFace       Gd       TA
1           80.0        0.0      1976.0  Grvl    BrkFace       Gd       TA
2           68.0      162.0      2001.0  Grvl    BrkFace       Gd       TA
3           60.0        0.0      1998.0  Grvl    BrkFace       TA       Gd
4           84.0      350.0      2000.0  Grvl    BrkFace       Gd       TA
5           85.0        0.0      1993.0  Grvl    BrkFace       Gd       TA
6           75.0      186.0      2004.0  Grvl      Stone       Ex       TA
7      70.049958      240.0      1973.0  Grvl      Stone       Gd       TA
8           51.0        0.0      1931.0  Grvl    BrkFace       TA       TA
9           50.0        0.0      1939.0  Grvl    BrkFace       TA       TA
10          70.0        0.0      1965.0  Grvl    BrkFace       TA       TA
11          85.0      286.0      2005.0  Grvl      Stone       Ex       TA
12     70.049958        0.0      1962.0  Grvl    BrkFace       TA       TA
13          91.0      306.0      2006.0  Grvl      Stone       Gd       TA
14     70.049958      212.0      1960.0  Grvl    BrkFace       TA       TA
15          51.0        0.0      1991.0  Grvl    BrkFace       TA       TA
16     70.049958      180.0      1970.0  Grvl    BrkFace       TA       TA
17          72.0        0.0      1967.0  Grvl    BrkFace       TA       TA
18          66.0        0.0      2004.0  Grvl    BrkFace       TA       TA
19          70.0        0.0      1958.0  Grvl    BrkFace       TA       TA
20         101.0      380.0      2005.0  Grvl    BrkFace       Ex       TA
21          57.0        0.0      1930.0  Grvl    BrkFace       TA       TA
22          75.0      281.0      2002.0  Grvl    BrkFace       Gd       TA
23          44.0        0.0      1976.0  Grvl    BrkFace       Gd       TA
24     70.049958        0.0      1968.0  Grvl    BrkFace       TA       TA
25         110.0      640.0      2007.0  Grvl      Stone       Gd       TA
26          60.0        0.0      2005.0  Grvl    BrkFace       TA       TA
27          98.0      200.0      2008.0  Grvl      Stone       Ex       TA
28          47.0        0.0      1957.0  Grvl    BrkFace       TA       TA
29          60.0        0.0      1920.0  Grvl    BrkFace       TA       TA
30          50.0        0.0      1920.0  Pave    BrkFace       TA       TA
31     70.049958        0.0      1966.0  Grvl    BrkFace       TA       TA
32          85.0        0.0      2007.0  Grvl    BrkFace       Ex       TA
33          70.0        0.0      1959.0  Grvl    BrkFace       TA       TA
34          60.0      246.0      2005.0  Grvl    BrkFace       Ex       TA
35         108.0      132.0      2004.0  Grvl      Stone       Ex       TA
36         112.0        0.0      1995.0  Grvl    BrkFace       Gd       TA
37          74.0      650.0      1954.0  Grvl    BrkFace       TA       TA
38          68.0        0.0      1953.0  Grvl    BrkFace       TA       TA
39          65.0        0.0      1980.0  Grvl    BrkFace       TA       TA
40          84.0      101.0      1965.0  Grvl    BrkFace       TA       TA
41         115.0        0.0      1959.0  Grvl    BrkFace       TA       TA
42     70.049958        0.0      1983.0  Grvl    BrkFace       Gd       TA
43     70.049958        0.0      1977.0  Grvl    BrkFace       Gd       TA
44          70.0        0.0      1959.0  Grvl    BrkFace       TA       TA
45          61.0      412.0      2005.0  Grvl    BrkFace       Ex       TA
46          48.0        0.0      2003.0  Grvl    BrkFace       Ex       TA
47          84.0        0.0      2006.0  Grvl    BrkFace       Gd       TA
48          33.0        0.0      1980.0  Grvl    BrkFace       TA       TA
49          66.0        0.0      1966.0  Grvl    BrkFace       TA       TA
50     70.049958        0.0      1997.0  Grvl    BrkFace       Gd       TA
51          52.0        0.0      1985.0  Grvl    BrkFace       TA       TA
52         110.0        0.0      1963.0  Grvl    BrkFace       Gd       TA
53          68.0        0.0      1981.0  Grvl    BrkFace       Ex       TA
54          60.0        0.0      1962.0  Grvl    BrkFace       TA       TA
55         100.0      272.0      1964.0  Grvl    BrkFace       TA       TA
56          24.0      456.0      1999.0  Pave    BrkFace       Gd       TA
57          89.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
58          66.0     1031.0      2006.0  Grvl    BrkFace       Ex       TA
59          60.0        0.0      1973.0  Grvl    BrkFace       TA       TA
60          63.0        0.0      2006.0  Grvl    BrkFace       Gd       TA
61          60.0        0.0      1935.0  Grvl    BrkFace       TA       Fa
62          44.0      178.0      2006.0  Grvl      Stone       Gd       Gd
63          50.0        0.0      1990.0  Grvl    BrkFace       TA       TA
64     70.049958      573.0      1998.0  Grvl    BrkFace       Gd       TA
65          76.0      344.0      2004.0  Grvl    BrkFace       Ex       TA
66     70.049958      287.0      1970.0  Grvl    BrkFace       Gd       TA
67          72.0      167.0      2003.0  Grvl    BrkFace       Gd       TA
68          47.0        0.0      1945.0  Grvl    BrkFace       TA       TA
69          81.0        0.0      1953.0  Grvl    BrkFace       TA       TA
70          95.0     1115.0      1973.0  Grvl    BrkFace       Gd       TA
71          69.0        0.0      1987.0  Grvl    BrkFace       TA       TA
72          74.0       40.0      1998.0  Grvl    BrkFace       Gd       TA
73          85.0      104.0      1989.0  Grvl    BrkFace       TA       TA
74          60.0        0.0      1915.0  Grvl    BrkFace       Fa       TA
75          21.0        0.0      1973.0  Grvl    BrkFace       Gd       TA
76     70.049958        0.0      1956.0  Grvl    BrkFace       TA       TA
77          50.0        0.0      1948.0  Grvl    BrkFace       TA       TA
78          72.0        0.0      1980.0  Grvl    BrkFace       TA       TA
79          60.0        0.0      1966.0  Grvl    BrkFace       TA       TA
80         100.0      576.0      1968.0  Grvl    BrkFace       Gd       TA
81          32.0      443.0      1998.0  Grvl    BrkFace       Ex       Gd
82          78.0      468.0      2007.0  Grvl      Stone       Gd       TA
83          80.0       66.0      1974.0  Grvl     BrkCmn       TA       TA
84     70.049958       22.0      1995.0  Grvl    BrkFace       Gd       TA
85         121.0      284.0      1991.0  Grvl    BrkFace       Gd       TA
86         122.0        0.0      2005.0  Grvl    BrkFace       Gd       TA
87          40.0       76.0      2009.0  Pave      Stone       Gd       TA
88         105.0        0.0      1980.0  Grvl    BrkFace       TA       Fa
89          60.0        0.0      1980.0  Grvl    BrkFace       Gd       TA
90          60.0        0.0      1950.0  Grvl    BrkFace       TA       TA
91          85.0      203.0      1961.0  Grvl     BrkCmn       TA       TA
92          80.0        0.0      1921.0  Grvl    BrkFace       Gd       TA
93          60.0        0.0      1900.0  Grvl    BrkFace       TA       Fa
94          69.0        0.0      1997.0  Grvl    BrkFace       Gd       TA
95     70.049958       68.0      1993.0  Grvl    BrkFace       Gd       Gd
96          78.0      183.0      1999.0  Grvl    BrkFace       Gd       TA
97          73.0       48.0      1965.0  Grvl    BrkFace       TA       TA
98          85.0        0.0      1920.0  Grvl    BrkFace       TA       TA
99          77.0        0.0      1980.0  Grvl    BrkFace       TA       TA
100    70.049958       28.0      1977.0  Grvl    BrkFace       TA       TA
101         77.0      336.0      1985.0  Grvl    BrkFace       Gd       TA
102         64.0        0.0      1979.0  Grvl    BrkFace       TA       TA
103         94.0        0.0      2009.0  Grvl    BrkFace       Gd       TA
104    70.049958      600.0      1951.0  Grvl    BrkFace       TA       TA
105         75.0      768.0      2003.0  Grvl    BrkFace       Ex       TA
106         60.0        0.0      1954.0  Grvl    BrkFace       Fa       TA
107         50.0        0.0      1948.0  Grvl    BrkFace       TA       TA
108         85.0        0.0      1980.0  Grvl    BrkFace       TA       TA
109        105.0      480.0      1977.0  Grvl    BrkFace       Gd       TA
110         75.0        0.0      1954.0  Grvl    BrkFace       TA       Fa
111    70.049958        0.0      2000.0  Grvl    BrkFace       Gd       TA
112         77.0      220.0      2007.0  Grvl      Stone       Ex       TA
113    70.049958      184.0      1953.0  Grvl    BrkFace       Gd       TA
114         61.0        0.0      1945.0  Grvl    BrkFace       TA       TA
115         34.0     1129.0      1999.0  Pave    BrkFace       Gd       TA
116    70.049958      116.0      1962.0  Grvl    BrkFace       TA       TA
117         74.0        0.0      2007.0  Grvl    BrkFace       Gd       TA
118         90.0        0.0      1990.0  Grvl    BrkFace       Gd       TA
119         65.0        0.0      2005.0  Grvl    BrkFace       Gd       TA
120    70.049958        0.0      1969.0  Grvl    BrkFace       TA       TA
121         50.0        0.0      1979.0  Grvl    BrkFace       TA       TA
122         75.0      135.0      1958.0  Grvl    BrkFace       TA       TA
123         55.0        0.0      1993.0  Grvl    BrkFace       Gd       TA
124         48.0        0.0      1979.0  Grvl    BrkFace       Gd       Fa
125         60.0        0.0      1980.0  Grvl    BrkFace       TA       TA
126    70.049958        0.0      1977.0  Grvl    BrkFace       Gd       TA
127         55.0        0.0      1980.0  Grvl    BrkFace       TA       TA
128         69.0      266.0      1966.0  Grvl    BrkFace       TA       TA
129         69.0       85.0      1998.0  Grvl    BrkFace       TA       TA
130         88.0      309.0      1966.0  Grvl    BrkFace       TA       TA
131    70.049958       40.0      2000.0  Grvl    BrkFace       Gd       TA
132         75.0        0.0      1974.0  Grvl    BrkFace       TA       TA
133    70.049958      136.0      2001.0  Grvl    BrkFace       Ex       TA
134         78.0        0.0      1968.0  Grvl    BrkFace       TA       TA
135         80.0      288.0      1970.0  Grvl    BrkFace       TA       TA
136    70.049958      196.0      1967.0  Grvl    BrkFace       TA       TA
137         82.0       70.0      1989.0  Grvl    BrkFace       TA       TA
138         73.0      320.0      1999.0  Grvl    BrkFace       Gd       TA
139         65.0        0.0      1997.0  Grvl    BrkFace       Gd       TA
140         70.0        0.0      1980.0  Grvl    BrkFace       TA       TA
141         78.0        0.0      2005.0  Grvl    BrkFace       Gd       TA
142         71.0        0.0      2000.0  Grvl    BrkFace       TA       TA
143         78.0      183.0      1999.0  Grvl    BrkFace       Gd       TA
144         70.0      336.0      1963.0  Grvl    BrkFace       TA       TA
145         24.0       50.0      2004.0  Grvl      Stone       Gd       TA
146         51.0        0.0      1931.0  Grvl    BrkFace       TA       TA
147    70.049958      180.0      2001.0  Grvl    BrkFace       Gd       TA
148         63.0      120.0      1980.0  Grvl    BrkFace       Gd       TA
149    70.049958        0.0      1936.0  Grvl    BrkFace       Gd       TA
150        120.0        0.0      1975.0  Grvl    BrkFace       TA       TA
151        107.0      436.0      2007.0  Grvl      Stone       Ex       TA
152    70.049958      252.0      1971.0  Grvl    BrkFace       TA       TA
153    70.049958        0.0      1960.0  Grvl    BrkFace       Gd       TA
154         84.0        0.0      1923.0  Grvl    BrkFace       TA       TA
155         60.0        0.0      1980.0  Grvl    BrkFace       TA       TA
156         60.0        0.0      1950.0  Grvl    BrkFace       TA       TA
157         92.0       84.0      2009.0  Grvl    BrkFace       Ex       TA
158        100.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
159        134.0      456.0      2006.0  Grvl    BrkFace       Gd       TA
160    70.049958        0.0      1984.0  Grvl    BrkFace       Gd       TA
161        110.0      664.0      2003.0  Grvl    BrkFace       Ex       TA
162         95.0      226.0      2005.0  Grvl    BrkFace       Gd       TA
163         55.0        0.0      1980.0  Grvl    BrkFace       TA       TA
164         40.0        0.0      1926.0  Pave    BrkFace       TA       TA
165         62.0        0.0      1980.0  Grvl    BrkFace       TA       TA
166    70.049958        0.0      1955.0  Grvl    BrkFace       TA       TA
167         86.0      300.0      2007.0  Grvl      Stone       Ex       TA
168         62.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
169    70.049958      653.0      1981.0  Grvl    BrkFace       Gd       TA
170    70.049958        0.0      1991.0  Grvl    BrkFace       TA       TA
171        141.0      112.0      1960.0  Grvl      Stone       TA       Gd
172         44.0        0.0      1987.0  Grvl    BrkFace       Gd       Gd
173         80.0      491.0      1961.0  Grvl     BrkCmn       TA       TA
174         47.0      132.0      1986.0  Grvl      Stone       Gd       Fa
175         84.0        0.0      1950.0  Grvl    BrkFace       TA       Gd
176         97.0      268.0      1988.0  Grvl    BrkFace       Gd       TA
177    70.049958        0.0      1958.0  Grvl    BrkFace       TA       TA
178         63.0      748.0      2009.0  Grvl      Stone       Ex       TA
179         60.0        0.0      1935.0  Grvl    BrkFace       TA       TA
180    70.049958      456.0      2000.0  Grvl    BrkFace       Gd       TA
181         54.0        0.0      1920.0  Grvl    BrkFace       Fa       TA
182         60.0       98.0      1957.0  Grvl    BrkFace       TA       TA
183         63.0        0.0      2003.0  Grvl    BrkFace       Gd       TA
184         92.0        0.0      1986.0  Grvl    BrkFace       Fa       TA
185         90.0        0.0      1993.0  Grvl    BrkFace       TA       TA
186    70.049958        0.0      1990.0  Grvl    BrkFace       Gd       TA
187         60.0        0.0      1916.0  Grvl    BrkFace       Fa       TA
188         64.0      275.0      1979.0  Grvl      Stone       Gd       TA
189         41.0        0.0      2001.0  Grvl    BrkFace       Ex       TA
190         70.0        0.0      1932.0  Grvl    BrkFace       Gd       Gd
191    70.049958      138.0      1972.0  Grvl    BrkFace       TA       TA
192         68.0        0.0      1999.0  Grvl    BrkFace       Gd       TA
193         24.0       50.0      2004.0  Grvl      Stone       Gd       TA
194         60.0        0.0      1989.0  Grvl    BrkFace       TA       TA
195         24.0        0.0      1976.0  Grvl    BrkFace       Gd       TA
196         79.0      205.0      2007.0  Grvl      Stone       Ex       TA
197        174.0        0.0      1918.0  Grvl    BrkFace       TA       TA
198         92.0        0.0      1980.0  Grvl    BrkFace       TA       TA
199         76.0      262.0      2004.0  Grvl    BrkFace       Ex       TA
200         80.0        0.0      2003.0  Grvl    BrkFace       Gd       TA
201         75.0        0.0      1980.0  Grvl    BrkFace       TA       TA
202         50.0        0.0      1924.0  Grvl    BrkFace       Fa       TA
203    70.049958      205.0      2004.0  Grvl    BrkFace       Gd       TA
204         50.0        0.0      1948.0  Grvl    BrkFace       TA       TA
205         99.0        0.0      1990.0  Grvl    BrkFace       Gd       TA
206         40.0        0.0      1962.0  Grvl    BrkFace       TA       TA
207    70.049958        0.0      1960.0  Grvl    BrkFace       TA       TA
208    70.049958      128.0      1988.0  Grvl    BrkFace       Gd       TA
209         75.0      260.0      1964.0  Grvl      Stone       Gd       TA
210         67.0        0.0      1980.0  Grvl    BrkFace       TA       TA
211         83.0        0.0      2009.0  Grvl    BrkFace       Gd       TA
212         72.0        0.0      2009.0  Grvl    BrkFace       Gd       TA
213         43.0        0.0      1996.0  Grvl    BrkFace       Gd       TA
214    70.049958      153.0      1977.0  Grvl    BrkFace       Gd       TA
215         72.0       64.0      1957.0  Grvl    BrkFace       TA       TA
216         65.0      266.0      2004.0  Grvl    BrkFace       Gd       TA
217         57.0        0.0      1940.0  Grvl    BrkFace       TA       TA
218    70.049958      312.0      1939.0  Grvl    BrkFace       TA       TA
219         43.0       16.0      2005.0  Grvl    BrkFace       Gd       TA
220         73.0        0.0      2006.0  Grvl    BrkFace       Gd       TA
221    70.049958        0.0      2002.0  Grvl    BrkFace       Gd       TA
222         85.0        0.0      1975.0  Grvl    BrkFace       Gd       TA
223         70.0        0.0      1989.0  Grvl    BrkFace       TA       TA
224        103.0      922.0      2003.0  Grvl    BrkFace       Ex       TA
225         21.0      142.0      1991.0  Grvl    BrkFace       TA       TA
226         82.0      290.0      1995.0  Grvl    BrkFace       Gd       TA
227         21.0      127.0      1987.0  Grvl    BrkFace       TA       TA
228         70.0        0.0      1974.0  Grvl    BrkFace       TA       TA
229         43.0       16.0      2005.0  Grvl    BrkFace       Gd       TA
230         73.0      220.0      1959.0  Grvl    BrkFace       TA       TA
231        174.0      506.0      1995.0  Grvl    BrkFace       Gd       TA
232         21.0      297.0      1972.0  Grvl    BrkFace       TA       TA
233         75.0        0.0      1976.0  Grvl    BrkFace       TA       Gd
234    70.049958        0.0      2002.0  Grvl    BrkFace       Gd       TA
235         21.0      604.0      1971.0  Grvl    BrkFace       TA       TA
236         65.0       98.0      2004.0  Grvl    BrkFace       Gd       TA
237    70.049958        0.0      1993.0  Grvl    BrkFace       Gd       TA
238         93.0      254.0      2007.0  Grvl    BrkFace       Ex       TA
239         52.0        0.0      1949.0  Grvl    BrkFace       TA       Fa
240         75.0       36.0      2008.0  Grvl      Stone       Gd       TA
241         40.0        0.0      1980.0  Grvl    BrkFace       TA       TA
242         63.0        0.0      1940.0  Grvl    BrkFace       TA       TA
243         75.0        0.0      1980.0  Grvl    BrkFace       Gd       TA
244    70.049958        0.0      1994.0  Grvl    BrkFace       Gd       TA
245         80.0      102.0      1988.0  Grvl    BrkFace       Gd       TA
246         69.0        0.0      1910.0  Grvl    BrkFace       Fa       TA
247         75.0        0.0      1954.0  Grvl    BrkFace       TA       TA
248         72.0      101.0      2003.0  Grvl    BrkFace       Gd       TA
249    70.049958      472.0      1958.0  Grvl     BrkCmn       Gd       TA
250         55.0        0.0      1980.0  Grvl    BrkFace       TA       TA
251         44.0      481.0      2006.0  Grvl      Stone       Gd       TA
252         65.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
253         85.0      108.0      1964.0  Grvl    BrkFace       Gd       TA
254         70.0        0.0      1957.0  Grvl    BrkFace       TA       TA
255         66.0      302.0      1999.0  Grvl    BrkFace       Gd       TA
256         64.0        0.0      2003.0  Grvl    BrkFace       Gd       TA
257         68.0      180.0      2006.0  Grvl      Stone       Gd       TA
258         80.0      172.0      2001.0  Grvl    BrkFace       Gd       TA
259         70.0        0.0      1956.0  Grvl    BrkFace       TA       TA
260        120.0      399.0      1991.0  Grvl    BrkFace       TA       TA
261         69.0      270.0      2007.0  Grvl      Stone       Ex       TA
262         88.0       46.0      1978.0  Grvl    BrkFace       Gd       Gd
263         50.0        0.0      1974.0  Grvl    BrkFace       TA       TA
264         30.0        0.0      1965.0  Grvl    BrkFace       Fa       TA

In [ ]:
# DISPLAY THE COMPLETE CLEANED TEST DATAFRAME
display(Complete_X_test)

     LotFrontage MasVnrArea GarageYrBlt Alley MasVnrType BsmtQual BsmtCond  \
0           80.0        0.0      1961.0  Grvl    BrkFace       TA       TA
1           81.0      108.0      1958.0  Grvl    BrkFace       TA       TA
2           74.0        0.0      1997.0  Grvl    BrkFace       Gd       TA
3           78.0       20.0      1998.0  Grvl    BrkFace       TA       TA
4           43.0        0.0      1992.0  Grvl    BrkFace       Gd       TA
5           75.0        0.0      1993.0  Grvl    BrkFace       Gd       TA
6      70.049958        0.0      1992.0  Grvl    BrkFace       Gd       TA
7           63.0        0.0      1998.0  Grvl    BrkFace       Gd       TA
8           85.0        0.0      1990.0  Grvl    BrkFace       Gd       TA
9           70.0        0.0      1970.0  Grvl    BrkFace       TA       TA
10          26.0        0.0      1999.0  Grvl    BrkFace       Gd       TA
11          21.0      504.0      1971.0  Grvl    BrkFace       TA       TA
12          21.0      492.0      1997.0  Grvl    BrkFace       TA       TA
13          24.0        0.0      1975.0  Grvl    BrkFace       TA       TA
14          24.0        0.0      1975.0  Grvl    BrkFace       Gd       TA
15         102.0      162.0      2009.0  Grvl      Stone       Ex       TA
16          94.0      256.0      2009.0  Grvl      Stone       Gd       TA
17          90.0      615.0      2005.0  Grvl    BrkFace       Ex       TA
18          79.0      240.0      2005.0  Grvl    BrkFace       Ex       TA
19         110.0     1095.0      2003.0  Grvl    BrkFace       Ex       TA
20         105.0      232.0      2002.0  Grvl    BrkFace       Gd       TA
21          41.0      178.0      2006.0  Grvl      Stone       Gd       TA
22         100.0        0.0      2005.0  Grvl    BrkFace       Gd       TA
23          43.0       14.0      2006.0  Grvl    BrkFace       Gd       TA
24          67.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
25          63.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
26          60.0      114.0      1998.0  Grvl    BrkFace       Ex       TA
27          73.0      226.0      2005.0  Grvl    BrkFace       Gd       TA
28          92.0        0.0      2009.0  Grvl    BrkFace       Gd       TA
29          84.0        0.0      2005.0  Grvl    BrkFace       Ex       TA
30          70.0      122.0      2004.0  Grvl    BrkFace       Gd       TA
31          70.0        0.0      1920.0  Grvl    BrkFace       TA       TA
32          39.0      250.0      1974.0  Grvl     BrkCmn       TA       TA
33          85.0      504.0      1993.0  Grvl    BrkFace       Gd       TA
34          88.0      180.0      1992.0  Grvl    BrkFace       Gd       TA
35          25.0        0.0      2004.0  Grvl    BrkFace       Ex       TA
36          39.0        0.0      2004.0  Pave    BrkFace       Gd       TA
37          30.0      120.0      2004.0  Pave    BrkFace       Gd       TA
38          24.0        0.0      2004.0  Pave    BrkFace       Gd       TA
39          24.0      216.0      2005.0  Pave    BrkFace       Gd       TA
40     70.049958     1159.0      2000.0  Grvl    BrkFace       Gd       TA
41     70.049958        0.0      2003.0  Grvl    BrkFace       Gd       TA
42          57.0        0.0      2010.0  Pave    BrkFace       Ex       Po
43          68.0        0.0      2000.0  Grvl    BrkFace       Gd       TA
44          80.0        0.0      2002.0  Grvl    BrkFace       Gd       TA
45     70.049958      120.0      1967.0  Grvl    BrkFace       TA       TA
46          80.0        0.0      1993.0  Grvl    BrkFace       Gd       TA
47     70.049958        0.0      1978.0  Grvl    BrkFace       Gd       TA
48          80.0        0.0      1971.0  Grvl    BrkFace       TA       TA
49          80.0      172.0      1966.0  Grvl    BrkFace       TA       TA
50          90.0        0.0      1966.0  Grvl    BrkFace       Gd       TA
51          88.0      268.0      1967.0  Grvl    BrkFace       TA       TA
52     70.049958        0.0      1964.0  Pave    BrkFace       TA       TA
53          98.0      144.0      1980.0  Grvl    BrkFace       TA       TA
54          68.0      265.0      1994.0  Grvl    BrkFace       TA       TA
55         120.0      340.0      1949.0  Grvl      Stone       TA       TA
56          75.0      216.0      1966.0  Grvl    BrkFace       TA       TA
57          70.0        0.0      1958.0  Grvl    BrkFace       TA       TA
58          70.0      506.0      2003.0  Grvl    BrkFace       Gd       TA
59     70.049958      150.0      1959.0  Grvl    BrkFace       TA       TA
60          87.0       91.0      1959.0  Grvl    BrkFace       TA       TA
61          80.0      432.0      1956.0  Grvl      Stone       TA       TA
62          60.0        0.0      1956.0  Grvl    BrkFace       TA       TA
63          60.0        0.0      1952.0  Grvl    BrkFace       TA       TA
64         119.0        0.0      1955.0  Grvl    BrkFace       TA       TA
65          70.0        0.0      1958.0  Grvl    BrkFace       TA       TA
66          65.0        0.0      1989.0  Grvl    BrkFace       TA       TA
67          60.0        0.0      1950.0  Grvl    BrkFace       TA       TA
68          81.0        0.0      1960.0  Grvl    BrkFace       TA       TA
69          80.0      218.0      1963.0  Grvl    BrkFace       TA       TA
70          60.0      771.0      1900.0  Grvl    BrkFace       TA       TA
71          56.0        0.0      1980.0  Grvl    BrkFace       TA       TA
72          69.0        0.0      1957.0  Grvl    BrkFace       TA       TA
73          50.0        0.0      1938.0  Grvl    BrkFace       Gd       TA
74          69.0        0.0      1948.0  Grvl    BrkFace       TA       TA
75     70.049958        0.0      1962.0  Grvl    BrkFace       TA       TA
76          68.0        0.0      1928.0  Grvl    BrkFace       Fa       Fa
77          60.0        0.0      1930.0  Grvl    BrkFace       TA       TA
78          50.0        0.0      2003.0  Grvl    BrkFace       Fa       Fa
79         100.0        0.0      1980.0  Grvl    BrkFace       TA       TA
80          60.0        0.0      1970.0  Grvl    BrkFace       Fa       TA
81          53.0        0.0      1950.0  Grvl    BrkFace       TA       TA
82     70.049958        0.0      1928.0  Grvl    BrkFace       Gd       TA
83          50.0        0.0      1926.0  Grvl    BrkFace       TA       TA
84          50.0        0.0      1939.0  Grvl    BrkFace       TA       Gd
85          50.0        0.0      1973.0  Grvl    BrkFace       TA       TA
86          53.0      300.0      1942.0  Grvl      Stone       TA       TA
87          50.0        0.0      1948.0  Grvl    BrkFace       TA       TA
88          52.0        0.0      1979.0  Grvl    BrkFace       TA       Fa
89          52.0        0.0      1930.0  Grvl    BrkFace       TA       TA
90          51.0        0.0      1923.0  Grvl    BrkFace       Fa       Fa
91          57.0        0.0      1915.0  Grvl    BrkFace       TA       TA
92          60.0        0.0      1980.0  Grvl    BrkFace       TA       TA
93          52.0        0.0      1920.0  Grvl    BrkFace       TA       TA
94         100.0       90.0      1959.0  Grvl    BrkFace       Gd       TA
95          72.0        0.0      1917.0  Grvl    BrkFace       Gd       Fa
96          60.0        0.0      1980.0  Grvl    BrkFace       TA       TA
97          65.0        0.0      1940.0  Grvl    BrkFace       Fa       TA
98     70.049958        0.0      1980.0  Grvl    BrkFace       TA       TA
99          60.0        0.0      1910.0  Grvl    BrkFace       TA       TA
100         72.0       72.0      1980.0  Grvl    BrkFace       TA       TA
101         65.0       47.0      1966.0  Grvl    BrkFace       TA       TA
102         65.0        0.0      1969.0  Grvl    BrkFace       TA       TA
103    70.049958        0.0      1978.0  Grvl    BrkFace       Gd       TA
104         86.0        0.0      1968.0  Grvl    BrkFace       TA       Gd
105    70.049958        0.0      1977.0  Grvl    BrkFace       Gd       TA
106         94.0        0.0      1945.0  Grvl    BrkFace       Fa       TA
107    70.049958      288.0      1978.0  Grvl    BrkFace       Gd       TA
108        124.0        0.0      1938.0  Grvl    BrkFace       TA       TA
109         65.0        0.0      1987.0  Grvl    BrkFace       TA       TA
110         50.0        0.0      1947.0  Grvl    BrkFace       TA       Fa
111         75.0        0.0      1954.0  Grvl    BrkFace       TA       TA
112         44.0       96.0      2009.0  Grvl      Stone       Gd       TA
113    70.049958        0.0      1964.0  Grvl    BrkFace       TA       TA
114         83.0      177.0      1987.0  Grvl    BrkFace       Gd       TA
115         87.0       85.0      2000.0  Grvl    BrkFace       Gd       TA
116         64.0       80.0      2009.0  Grvl      Stone       Gd       TA
117         82.0        0.0      1957.0  Grvl    BrkFace       Fa       Gd
118         82.0        0.0      1998.0  Grvl    BrkFace       Gd       Fa
119    70.049958        0.0      1997.0  Grvl    BrkFace       Gd       TA
120         38.0        0.0      1977.0  Grvl    BrkFace       Gd       TA
121         68.0        0.0      1977.0  Grvl    BrkFace       TA       TA
122         80.0      320.0      2003.0  Grvl    BrkFace       Gd       TA
123         75.0        0.0      1997.0  Grvl    BrkFace       Gd       TA
124    70.049958      170.0      2003.0  Grvl    BrkFace       Gd       TA
125         67.0        0.0      1945.0  Grvl    BrkFace       TA       TA
126         68.0        0.0      1954.0  Grvl    BrkFace       Fa       TA
127         60.0        0.0      1968.0  Grvl    BrkFace       Gd       TA
128         89.0        0.0      1956.0  Grvl    BrkFace       TA       TA
129         65.0        0.0      1975.0  Grvl    BrkFace       TA       TA
130         64.0        0.0      1980.0  Grvl    BrkFace       TA       TA
131         67.0      203.0      1979.0  Grvl    BrkFace       TA       TA
132    70.049958        0.0      1939.0  Grvl    BrkFace       TA       TA
133         60.0        0.0      1980.0  Pave    BrkFace       TA       TA
134         51.0        0.0      1980.0  Grvl    BrkFace       TA       Fa
135         78.0      371.0      1941.0  Grvl    BrkFace       Gd       TA
136         78.0      430.0      1950.0  Grvl    BrkFace       TA       TA
137         85.0       44.0      1994.0  Grvl    BrkFace       Gd       TA
138         35.0        0.0      1989.0  Grvl    BrkFace       Gd       TA
139         35.0        0.0      1989.0  Grvl    BrkFace       Gd       TA
140         58.0        0.0      1951.0  Grvl    BrkFace       TA       TA
141         50.0        0.0      1950.0  Grvl    BrkFace       TA       TA
142         66.0        0.0      1896.0  Grvl    BrkFace       TA       TA
143         44.0      186.0      2004.0  Grvl      Stone       Ex       TA
144         85.0        0.0      1998.0  Grvl    BrkFace       Gd       TA
145         74.0        0.0      1977.0  Grvl    BrkFace       TA       TA
146    70.049958        0.0      1976.0  Grvl    BrkFace       TA       TA
147         88.0       60.0      2008.0  Grvl      Stone       Gd       TA
148         73.0        0.0      2010.0  Grvl    BrkFace       Gd       TA
149         73.0        0.0      2007.0  Grvl    BrkFace       Gd       TA
150         85.0        0.0      1965.0  Grvl    BrkFace       TA       TA
151         93.0        0.0      2004.0  Grvl    BrkFace       Ex       TA
152    70.049958        0.0      2001.0  Grvl    BrkFace       Gd       TA
153         31.0        0.0      1973.0  Grvl    BrkFace       Gd       TA
154         21.0        0.0      1980.0  Grvl    BrkFace       TA       TA
155         21.0        0.0      1980.0  Grvl    BrkFace       TA       TA
156         21.0        0.0      1972.0  Grvl    BrkFace       TA       TA
157         50.0        0.0      1971.0  Grvl    BrkFace       TA       TA
158         76.0        0.0      1984.0  Grvl    BrkFace       Gd       TA
159         70.0        0.0      1985.0  Grvl    BrkFace       TA       TA
160         63.0        0.0      1993.0  Grvl    BrkFace       Gd       TA
161         68.0        0.0      1969.0  Grvl    BrkFace       TA       TA
162         76.0        0.0      1994.0  Grvl    BrkFace       Gd       Gd
163         74.0        0.0      1993.0  Grvl    BrkFace       Gd       TA
164         74.0        0.0      1956.0  Grvl    BrkFace       Fa       Fa
165         85.0      440.0      1974.0  Grvl    BrkFace       TA       TA
166         88.0        0.0      1997.0  Grvl    BrkFace       Gd       TA
167    70.049958      188.0      2003.0  Grvl    BrkFace       Gd       TA
168         60.0       32.0      1996.0  Grvl    BrkFace       Gd       TA
169         28.0        0.0      2004.0  Grvl    BrkFace       Ex       TA
170         61.0        0.0      1998.0  Grvl    BrkFace       Gd       TA
171         57.0        0.0      1995.0  Grvl    BrkFace       Gd       TA
172         57.0        0.0      1998.0  Grvl    BrkFace       Gd       TA
173         60.0        0.0      1998.0  Grvl    BrkFace       Gd       TA
174    70.049958        0.0      1994.0  Grvl    BrkFace       Gd       TA
175         58.0       45.0      1993.0  Grvl    BrkFace       Gd       TA
176         85.0      157.0      1977.0  Grvl    BrkFace       Gd       TA
177    70.049958      256.0      1978.0  Grvl    BrkFace       Gd       TA
178         80.0      101.0      1978.0  Grvl    BrkFace       TA       TA
179    70.049958      229.0      1980.0  Grvl    BrkFace       Gd       TA
180         80.0      144.0      1978.0  Grvl    BrkFace       TA       TA
181         70.0        0.0      2003.0  Grvl    BrkFace       Gd       TA
182    70.049958        0.0      2000.0  Grvl    BrkFace       Gd       TA
183    70.049958        0.0      2002.0  Grvl    BrkFace       Gd       TA
184    70.049958      161.0      1975.0  Grvl    BrkFace       Gd       TA
185         78.0      196.0      1974.0  Grvl    BrkFace       TA       TA
186         85.0        0.0      1975.0  Grvl    BrkFace       TA       TA
187    70.049958        0.0      1970.0  Grvl    BrkFace       TA       TA
188    70.049958      178.0      1971.0  Grvl    BrkFace       Gd       TA
189         60.0        0.0      2001.0  Grvl    BrkFace       TA       TA
190         60.0        0.0      1986.0  Grvl    BrkFace       TA       TA
191         21.0      504.0      1973.0  Grvl    BrkFace       TA       TA
192         21.0      425.0      1972.0  Grvl    BrkFace       TA       TA
193         24.0        0.0      1976.0  Grvl    BrkFace       Gd       TA
194         24.0        0.0      1975.0  Grvl    BrkFace       Gd       TA
195         24.0        0.0      1977.0  Grvl    BrkFace       Gd       TA
196         24.0        0.0      1978.0  Grvl    BrkFace       Gd       TA
197         24.0        0.0      1978.0  Grvl    BrkFace       Gd       TA
198         24.0        0.0      1976.0  Grvl    BrkFace       TA       TA
199    70.049958      165.0      1966.0  Grvl    BrkFace       TA       TA
200        110.0      726.0      2007.0  Grvl      Stone       Ex       TA
201         95.0        0.0      2009.0  Grvl    BrkFace       Ex       TA
202         95.0      450.0      2008.0  Grvl      Stone       Ex       TA
203        105.0      472.0      2007.0  Grvl      Stone       Ex       TA
204         95.0      302.0      2008.0  Grvl      Stone       Ex       TA
205        129.0      238.0      2004.0  Grvl    BrkFace       Ex       TA
206         59.0       20.0      2007.0  Grvl      Stone       Ex       TA
207         87.0      284.0      2008.0  Grvl      Stone       Ex       TA
208         77.0      122.0      2006.0  Grvl      Stone       Ex       Gd
209        102.0      285.0      2008.0  Grvl    BrkFace       Ex       TA
210         90.0      418.0      2003.0  Grvl    BrkFace       Gd       TA
211        110.0      724.0      2003.0  Grvl    BrkFace       Ex       TA
212         96.0      186.0      2003.0  Grvl      Stone       Gd       TA
213         70.0      383.0      2006.0  Grvl      Stone       Gd       TA
214         47.0      240.0      2005.0  Grvl      Stone       Gd       TA
215         34.0      135.0      2005.0  Grvl      Stone       Gd       TA
216         80.0      176.0      2008.0  Grvl      Stone       Gd       TA
217        100.0      730.0      2004.0  Grvl      Stone       Ex       TA
218        117.0      470.0      2003.0  Grvl    BrkFace       Ex       TA
219         44.0      308.0      2008.0  Grvl    BrkFace       Ex       TA
220         48.0      500.0      2008.0  Grvl    BrkFace       Ex       TA
221        129.0      270.0      2002.0  Grvl    BrkFace       Ex       TA
222         48.0      163.0      2003.0  Grvl      Stone       Gd       TA
223         63.0        0.0      2005.0  Grvl    BrkFace       Gd       Gd
224         57.0        0.0      2005.0  Grvl    BrkFace       Gd       TA
225         43.0       16.0      2005.0  Grvl    BrkFace       Gd       TA
226         59.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
227         62.0      200.0      2004.0  Grvl    BrkFace       Gd       TA
228         61.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
229    70.049958        0.0      2003.0  Grvl    BrkFace       Gd       TA
230    70.049958        0.0      2003.0  Grvl    BrkFace       Gd       TA
231    70.049958        0.0      2002.0  Grvl    BrkFace       Ex       TA
232         61.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
233         42.0        0.0      2000.0  Grvl    BrkFace       Gd       TA
234         62.0        0.0      1999.0  Grvl    BrkFace       Gd       TA
235    70.049958      210.0      1999.0  Grvl    BrkFace       Gd       TA
236         64.0        0.0      1999.0  Grvl    BrkFace       TA       TA
237        106.0      150.0      2000.0  Grvl    BrkFace       Gd       TA
238    70.049958      634.0      1994.0  Grvl    BrkFace       Gd       TA
239         79.0      286.0      1995.0  Grvl    BrkFace       Gd       TA
240    70.049958      372.0      1993.0  Grvl    BrkFace       Gd       TA
241         86.0      240.0      2008.0  Grvl      Stone       Gd       TA
242         78.0      294.0      2008.0  Grvl    BrkFace       Gd       TA
243         85.0      260.0      2007.0  Grvl      Stone       Gd       TA
244         76.0      206.0      2006.0  Grvl      Stone       Ex       TA
245         85.0      198.0      2005.0  Grvl      Stone       Ex       TA
246         90.0        0.0      2008.0  Grvl    BrkFace       Ex       TA
247         72.0        0.0      2008.0  Grvl    BrkFace       Gd       TA
248        112.0      120.0      2008.0  Grvl      Stone       Gd       TA
249         75.0      238.0      2006.0  Grvl      Stone       Gd       TA
250         84.0      121.0      2006.0  Grvl      Stone       Ex       Gd
251         65.0      288.0      2009.0  Grvl    BrkFace       Gd       TA
252         85.0        0.0      2006.0  Grvl    BrkFace       Gd       TA
253         68.0        0.0      2003.0  Grvl    BrkFace       Gd       TA
254         65.0        0.0      2003.0  Grvl    BrkFace       Gd       TA
255         80.0        0.0      2007.0  Grvl    BrkFace       Gd       TA
256         63.0        0.0      2006.0  Grvl    BrkFace       Gd       Gd
257         63.0        0.0      1980.0  Grvl    BrkFace       Gd       TA
258         96.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
259         76.0      264.0      2004.0  Grvl    BrkFace       Gd       TA
260         63.0        0.0      2005.0  Grvl    BrkFace       Gd       TA
261         63.0        0.0      1980.0  Grvl    BrkFace       Gd       TA
262         60.0        0.0      2004.0  Grvl    BrkFace       Gd       TA
263         61.0      140.0      2008.0  Grvl    BrkFace       Gd       TA
264         43.0      132.0      1997.0  Grvl    BrkFace       Gd       TA

In [ ]:
# CALCULATE TOTAL MISSING VALUES IN THE CLEANED DATASETS
Null_Miss1 = Complete_X_train.isnull().sum().sum()
Null_Miss2 = Complete_X_train.isnull().sum().sum()

# DISPLAY FINAL SHAPES OF CLEANED DATASETS
print(f":> CLEANED TRAINING DATASET SHAPE: {Complete_X_train.shape}")
print(f":> CLEANED TEST DATASET SHAPE: {Complete_X_test.shape}")

# DISPLAY FINAL MISSING VALUE COUNTS (SHOULD BE ZERO)
print(f"\n:> TOTAL MISSING VALUES IN TRAINING DATASET (FINAL): {Null_Miss1}")
print(f":> TOTAL MISSING VALUES IN TEST DATASET (FINAL): {Null_Miss2}")

:> CLEANED TRAINING DATASET SHAPE: (1460, 19)
:> CLEANED TEST DATASET SHAPE: (1459, 19)

:> TOTAL MISSING VALUES IN TRAINING DATASET (FINAL): 0
:> TOTAL MISSING VALUES IN TEST DATASET (FINAL): 0